config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#index'
  resources :events, except: :index
  get '/past', to: 'events#past'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates_presence_of :name, :venue, :description, :start_time, :end_time
  validates :description, length: { minimum: 10, maximum: 1000 }
  validate :end_time_gt_start_time

  mount_uploader :picture, EventPictureUploader

  before_validation :make_start_end_times

  default_scope { order(start_time: :desc) }

  scope :upcoming, -> { where("end_time > ?", Time.now()) }
  scope :past, -> { where("end_time <= ?", Time.now()) }

  attr_accessor :start_date, :end_date

  private

  def make_start_end_times
    if start_date && start_time
      str = "#{start_date}T" + start_time.strftime('%H:%M')
      self.start_time = Time.parse(str)
    end
    if end_date && end_time
      str = "#{end_date}T" + end_time.strftime('%H:%M')
      self.end_time = Time.parse(str)
    end
  end

  def end_time_gt_start_time
    if start_time && end_time && start_time >= end_time
      errors.add(:end_time, "should be later than start time")
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.upcoming
    @heading = "Upcoming events"
  end

  def past
    @events = Event.past
    @heading = "Past events"
    render :index
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :venue, :start_time, :end_time, :description, :start_date, :end_date, :picture)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def format_date(datetime)
    return nil unless datetime.respond_to?(:strftime)

    datetime.localtime.strftime("%Y-%m-%d %H:%M")
  end
end

app/views/events/_event.html.erb
<%= link_to event do %>
<div class="event_item card">
  <div class="card__image_container">
    <% if event.picture.file %>
      <%= image_tag event.picture.url, class: 'card__image' %>
    <% else %>
      <picture>
        <source type="image/jpeg" media="(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)" srcset="<%= image_path("placeholder_2x.jpg") %>" />
        <source type="image/jpeg" srcset="<%= image_path("placeholder.jpg") %>" />
        <%= image_tag "placeholder.jpg" %>
      </picture>
    <% end %>
  </div>
  <div class="card__content">
    <p class="event_item__name"><%= event.name %></p>
    <p class="event_item__venue"><%= event.venue %></p>
    <p class="event_item__start_time"><%= format_date(event.start_time) %></p>
  </div>
</div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, multipart: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_field :venue %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.date_field :start_date, value: event.start_time&.to_date %>
    <%= form.time_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.date_field :end_date, value: event.end_time&.to_date %>
    <%= form.time_field :end_time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<section class="page_header">
<h1><%= @heading %></h1>
<%= link_to 'New Event', new_event_path, class: 'button push-right' %>
</section>

<div class="event_grid">
<%= render partial: "event", collection: @events %>
</div>

app/views/events/new.html.erb
<a href="/">&lt;&lt; Back</a>
<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= link_to '<< Back', '/' %>

<div class="card single_event">
  <div class="card__image_container">
    <% if @event.picture.file %>
      <%= image_tag @event.picture.url, class: 'single_event__image single_event__image--move-up' %>
    <% else %>
      <%= image_tag 'placeholder_wide.jpg', class: 'single_event__image' %>
    <% end %>
  </div>
  <div class="single_event__details card__content">
    <h3 class="single_event__name"><%= @event.name %></h3>
    <%= link_to 'Edit', edit_event_path(@event) %>
    <p id="notice"><%= notice %></p>
    <p><strong>Venue:</strong> <%= @event.venue %></p>

    <p><strong>Time:</strong> <%= @event.start_time %> till <%= @event.end_time %></p>
    <div class="single_event__description"><%= @event.description %></div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container header__container">
    <%= link_to '/' do %>
      <%= image_tag 'amagumo-logo.svg', class: 'header__logo' %>
    <% end %>

    <%= link_to 'Upcoming', '/', class: 'push-right header__link' %>
    <%= link_to 'Past Events', '/past', class: 'header__link' %>
    <%= link_to 'New Event', '/events/new', class: 'header__cta header__link button' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amagumo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,600i,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container">
      <%= yield %>
    </main>
    <footer>
      <div class="container">
        &copy; 2019 by Karol Moroz / Cogini Hong Kong Limited. All rights reserved.
      </div>
    </footer>
  </body>
</html>